# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:jmuthialu/PodSpecRepo.git'

target 'DemoApp' do
  use_frameworks!

# To create a dev pos use :path. This allows you directly modify the source code
# pod 'LoggingFramework', :path => '../'

# This will create non editable pod
  pod 'LoggingFramework', '0.0.2'

end
