# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:jmuthialu/PodSpecRepo.git'

target 'DemoApp' do
  use_frameworks!

#  pod 'LoggingFramework', :path => '../'
  pod 'LoggingFramework', '0.0.1'

end
